# host-specific zsh config

alias lsrc='lsrc -B YELP-EMW'
alias mkrc='mkrc -B YELP-EMW'
alias rcup='rcup -B YELP-EMW'

[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*

export NVM_DIR="/Users/emw/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm
