# host-specific zsh config

alias tugboat='rvm 1.9.3-p448 do tugboat'
export NVM_DIR="/Users/herooftime/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm
export PATH="$PATH:$HOME/.rvm/bin" # Add RVM to PATH for scripting

export JIRA_URL="https://issues.openmrs.org"
#
#THIS MUST BE AT THE END OF THE FILE FOR GVM TO WORK!!!
[[ -s "/Users/herooftime/.gvm/bin/gvm-init.sh" ]] && source "/Users/herooftime/.gvm/bin/gvm-init.sh"

PERL_MB_OPT="--install_base \"/home/herooftime/perl5\""; export PERL_MB_OPT;
PERL_MM_OPT="INSTALL_BASE=/home/herooftime/perl5"; export PERL_MM_OPT;
