#!/bin/zsh
function reagent {
    . ~/.ssh/latestagent
}

function rename {
    if [ -n "$1" ]; then
        tmux set allow-rename off
        tmux renamew $1
    else
        tmux set allow-rename on
    fi
}

function tmux-cd {
    name=$(tmux list-sessions | grep attached | sed -e 's/^\([A-Za-z0-9]*\):.*/\1/')
    if [ -d "$HOME/Dropbox/$name" ]; then
        cd "$HOME/Dropbox/$name"
    fi
}

alias bye='clear && tmux clear-history'
